version: '3'
    
services:
  portfolio:
    build: .
    hostname: portfolio
    networks:
      - frontend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
networks:
  frontend:
    external: true